wit_bindgen::generate!("host");

use linfa_linalg::qr::*;
use ndarray::prelude::*;

struct MyHost;

impl Host for MyHost {
    fn run() {
        println!("HOGEHOGE");
        let a = array!(
            [1.0e-20, 0.0, 0.0, 0.0, 0.0],
            [0.0, 1.0e-20, 0.0, 0.0, 0.0],
            [0.0, 0.0, 1.0e-20, 0.0, 0.0],
            [0.0, 0.0, 0.0, 1.0e-20, 0.0],
            [0.0, 0.0, 0.0, 0.0, 1.0e-20],
        );
        let a_inv = a.qr_into().unwrap().inverse().unwrap();
        println!("{:?}", a_inv);
        print("Hello, world!");
    }
}

// The following macro is generated by wit-bindgen and is always named `export_{world_name}`
export_host!(MyHost);
