[package]
name = "guest"
version = "0.1.0"
rust-version = "1.71.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
linfa-linalg = "0.1.0"
ndarray = "0.15.6"
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", version="0.9.0" }
